### ISSUE TITLE
which openssl version

### ISSUE THREAD

**Issue by bncdemo** [asnefedovv/dydx-v4-client-cpp#2]
The build fail with the latest openssl version?
![cm](https://github.com/asnefedovv/dydx-v4-client-cpp/assets/63590595/fc584ab5-829e-4acb-bf06-716e17436f1a)

**Comment by asnefedovv** [comment]
I tested it on Ubuntu 24.10 with OpenSSL 3.2.2 and it works. Make sure you have `libssl-dev` installed.
